export const nfts = [
  {
    index: 1,
    imgUrl: '/assets/Alladin.png',
    info: 'Some Alladin info',
    title: "Alladin",
    link: '/alladin.com',
  },
  {
    index: 2,
    imgUrl: '/assets/Duck.png',
    info: 'Some Duck info',
    title: "Duck",
    link: '/duck.com',
  },
  {
    index: 3,
    imgUrl: '/assets/Frogger.png',
    info: 'Some Frogger info',
    title: "Frogger",
    link: '/frogger.com',
  },
  {
    index: 4,
    imgUrl: '/assets/Tank.png',
    info: 'Germany / Ultra-rare / Armor 80 / Damage 50',
    title: "Panzer 4",
    link: '/apple.com',
  },
  {
    index: 5,
    imgUrl: '/assets/Grenade.png',
    info: 'Some Grenade info',
    title: "Grenade",
    link: '/grenade.com',
  },
  {
    index: 6,
    imgUrl: '/assets/SuperMario.png',
    info: 'Some super Mario info',
    title: "Super Mario",
    link: '/google.com',
  },
  {
    index: 7,
    imgUrl: '/assets/Pac-Man.png',
    info: 'Some Pac-Man info',
    title: "Pac-Man",
    link: '/yandex.ru',
  },
];
